# 错误处理规范

编程中，错误总容易在发生后再进行处理，其实错误应该在编码之时就纳入考虑

## 错误类型

### 错误

可以预测

### 异常

不可恢复则定义为异常

## 错误处理方式

对于可以预测的错误，一般采用check方式处理

```js
int foo() {
    // <try something here>
    if (failed) {
        return 1;
    }
    return 0;
}

int err = foo();
if (err) {
    // Error!  Deal with it.
}
 
```

##  异常处理方式

## 同步处理

try-catch-finally
```js
  try{
    // 可能发生异常的代码
    someFunction()
  } catch(error){
    if(error instanceof TypeError){
      //处理类型错误
    } else if (error instanceof ReferenceError) {
      //处理引用错误
    } else {
      //处理其他错误
    }
  } finally {
    // 始终要做的 比如关闭数据库连接
  }
```

### 异步处理


#### callback

```js
// 如果fn出错，try-catch无法捕获
try {
  setTimeout(fn,0)
}catch {
  // error handle
}
```

可以在fn本身加入try-catch来处理异常，但是不推荐,推荐使用window.error来捕获

```js
window.addEventListener('error', function (e) {
    var error = e.error;
    console.log(error);
})
```

#### promise

对于promise而言，需要使用catch来捕获异步错误，这在一些浏览器中还可以观察其调用栈

```js
p1.then().catch()
```

#### await、async

await可以像同步方式处理错误

```js
try {
  await p 
} catch {
  // error handle
}
```


## 参考文章

https://segmentfault.com/a/1190000018538740



